version: '3'
name: activity-app
services:
  php:
    build:
      context: ./php
      dockerfile: ./Dockerfile
      args:
        TIMEZONE: 'Europe/Madrid'
    environment:
      APP_ENV: dev
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9000
      PHP_IDE_CONFIG: serverName=localhost
    volumes:
      - ../:/var/www/
    networks:
      - activity-app-network
  db:
    image: mariadb:10.7.4
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - activity-app-network
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - ../:/var/www/
    ports:
      - '8080:80'
    networks:
      - activity-app-network
networks:
  activity-app-network: