parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Shared\Domain\Bus\Command\CommandHandler:
      tags: [ 'app.command_handler' ]

    App\Shared\Domain\Bus\Query\QueryHandler:
      tags: [ 'app.query_handler' ]

  App\:
    resource: '../src/App/*'

  UI\:
    resource: '../src/UI/*'

  UI\Http\Rest\Controller\:
    resource: '../src/UI/Http/Rest/Controller/*'
    tags: [ 'controller.service_arguments' ]


  App\Shared\Infrastructure\Bus\Command\InMemoryCommandBus:
    arguments: [ !tagged app.command_handler ]

  App\Shared\Infrastructure\Bus\Query\InMemoryQueryBus:
    arguments: [ !tagged app.query_handler ]